### ISSUE TITLE
msbuild uses HostX86 tools when cross-compiling on x64 host and UseEnv=false

### ISSUE THREAD

**Issue by huangqinjin** [mstorsjo/msvc-wine#108]
x86: https://github.com/mstorsjo/msvc-wine/actions/runs/7688417957/job/20949618574#step:5:169
>   z:\home\runner\work\msvc-wine\msvc-wine\msvc\vc\tools\msvc\14.38.33130\bin\HostX86\x86\CL.exe /c /Zi /nologo /W3 /WX- /diagnostics:column /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Z:/tmp/msvc-wine.tmp.BKU5/useenv-false/Debug/" /Fd"Z:/tmp/msvc-wine.tmp.BKU5/useenv-false/Debug/vc143.pdb" /external:W3 /Gd /TP /analyze- /FC /errorReport:queue HelloWorld.cpp

arm: https://github.com/mstorsjo/msvc-wine/actions/runs/7688417957/job/20949618574#step:5:639
>   z:\home\runner\work\msvc-wine\msvc-wine\msvc\vc\tools\msvc\14.38.33130\bin\HostX86\arm\CL.exe /c /Zi /nologo /W3 /WX- /diagnostics:column /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1 /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Z:/tmp/msvc-wine.tmp.nS3F/useenv-false/Debug/" /Fd"Z:/tmp/msvc-wine.tmp.nS3F/useenv-false/Debug/vc143.pdb" /external:W3 /Gd /TP /analyze- /FC /errorReport:queue HelloWorld.cpp

arm64: https://github.com/mstorsjo/msvc-wine/actions/runs/7688417957/job/20949618574#step:5:872
>   z:\home\runner\work\msvc-wine\msvc-wine\msvc\vc\tools\msvc\14.38.33130\bin\HostX86\arm64\CL.exe /c /Zi /nologo /W3 /WX- /diagnostics:column /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _ARM64_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1 /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Z:/tmp/msvc-wine.tmp.8ncV/useenv-false/Debug/" /Fd"Z:/tmp/msvc-wine.tmp.8ncV/useenv-false/Debug/vc143.pdb" /external:W3 /Gd /TP /analyze- /FC /errorReport:queue HelloWorld.cpp

CC @ravenexp

**Comment by ravenexp** [comment]
This is quite interesting... Using HostX86 tools is something MSBuild decides by itself when `UseEnv=false`. There must be some kind of a property governing these choices.

Thanks for noticing, I'll look into it.

**Comment by ravenexp** [comment]
I believe it's fixed in #109 :

- x86: https://github.com/mstorsjo/msvc-wine/actions/runs/7760677042/job/21167440170?pr=109#step:5:169
- arm: https://github.com/mstorsjo/msvc-wine/actions/runs/7760677042/job/21167440170?pr=109#step:5:624
- arm64: https://github.com/mstorsjo/msvc-wine/actions/runs/7760677042/job/21167440170?pr=109#step:5:857
