### ISSUE TITLE
CMake Find Packages

### ISSUE THREAD

**Issue by PatchByte** [mstorsjo/msvc-wine#114]
How to use packages such as Vulkan.
Like if you would want to do:
```
find_package(Vulkan REQUIRED)
```
The problem is cmake would try to search after the linux package. I have not found any way to fix this.

**Comment by mstorsjo** [comment]
When cross compiling with CMake, you need to set a bunch of cmake flags to tell it where/how to look for things, and what not to look for. One way of configuring those flags, which might work, is something like this:
```
-DCMAKE_FIND_ROOT_PATH=$CROSS_ROOT
-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
```
