### ISSUE TITLE
Should no longer use Ubuntu 19.04 as the base docker image

### ISSUE THREAD

**Issue by Cryspia** [mstorsjo/msvc-wine#12]
According to the [description from Ubuntu](https://hub.docker.com/_/ubuntu), the Ubuntu 19.04 docker image is no longer officially support. As a result, the _apt_ server is turned down, and a docker image or container cannot use _apt_ to install or upgrade any packages.

This project is also affected since it uses _apt_ commands in the dockerfile so that the build will fail on the unreachable _apt_ server. To solve this problem, you may want to upgrade to version 19.10 or 20.04.

Personally, I would suggest 20.04 because it is a LTS version although it is still in beta.

**Comment by mstorsjo** [comment]
Thanks for pointing it out.

I pushed a fix in ed08a19a5e82fe9294bbe1cf97df0a39153cf96e. I only went for 19.10 at the moment, as there seems to be some issues with the wine version in Ubuntu 20.04 when running cl.exe (see the commit message of that commit for details).

**Comment by mstorsjo** [comment]
FWIW, I managed to get it to work with Ubuntu 20.04, see the branch `ubuntu-2004`. But as I pushed the fix to use 19.10 for now, I'll keep it that way until 20.04 is officially released at least.
