### ISSUE TITLE
ATL headers

### ISSUE THREAD

**Issue by niansa** [mstorsjo/msvc-wine#142]
Hey!

Apparently there are no ATL headers including `atlbase.h` which are required for some applications to compile.
Would be neat to have those!

Thanks

**Comment by mstorsjo** [comment]
See #143, that should provide the ATL headers.

**Comment by niansa** [comment]
Nice! Thanks.

**Comment by mstorsjo** [comment]
I merged #143 now, so this should be fixed now.
