### ISSUE TITLE
Hi, does this let me run the MSVC++ IDE on Linux through wine?

### ISSUE THREAD

**Issue by CrazyPython** [mstorsjo/msvc-wine#2]

**Comment by mstorsjo** [comment]
No, this only allows you running the command line tools.

**Comment by CrazyPython** [comment]
Can I compile with `/Analyze` on? Will it give me the analyzer warnings?

Additionally, is this known if this works on MacOS?

**Comment by mstorsjo** [comment]
I haven't tested with `/Analyze`, maybe it works, maybe it doesn't.

I haven't tested using it on macOS - it might work.
