### ISSUE TITLE
Remove VCTIP.exe

### ISSUE THREAD

**Issue by mahkoh** [mstorsjo/msvc-wine#23]
The VCTIP executable is bugged and can cause cl.exe to hang. Removing it seems to have no adverse effects and fixes the hang. Please remove all VCTIP.exe instances during the installation process as per https://bugs.chromium.org/p/chromium/issues/detail?id=735226

**Comment by mstorsjo** [comment]
Fixed in 49461b3e93209b5d3e9b53fa9df81acac869fa18.
