### ISSUE TITLE
Create wrappers to use MSVC tools in a Unix way

### ISSUE THREAD

**Issue by falhumai96** [mstorsjo/msvc-wine#24]
Is it possible to create `CC` and `CXX` wrappers for the MSVC `cl` compiler with Unix interface (e.g. similar to Clang/LLVM or GCC in Unix) that wraps around Unix interface flags to the matching ones in `cl`, so it can be used in Autoconf based projects?

**Comment by mstorsjo** [comment]
Yes, it is possible, various projects have done this.

See e.g. https://github.com/libffi/libffi/blob/master/msvcc.sh and https://git.videolan.org/?p=vlc/vlc-msvc.git;a=blob;f=wrappers/clwrap;h=18d75d455b993a7dbfbce24bb5a524cbdb0dc47a;hb=73c299b2e50f53eea755973cf1a1ddc5794a1837.

It's not something I'm planning on adding in this repo though.

**Comment by falhumai96** [comment]
awesome, thx for linking these projects
