### ISSUE TITLE
What is this error? Did I compile successfully or failed?

### ISSUE THREAD

**Issue by zuowanbushiwo** [mstorsjo/msvc-wine#26]
Hi mstorsjo
Thank you very much for sharing this project ,my local compilation has the following errors. Did I succeed or fail?
![image](https://user-images.githubusercontent.com/3354428/130359679-293247cc-9703-4d28-a217-075482049681.png)

**Comment by mstorsjo** [comment]
Those messages are from wine, and are normal.

**Comment by zuowanbushiwo** [comment]
thanks!
