### ISSUE TITLE
Kernel-mode headers

### ISSUE THREAD

**Issue by maharmstone** [mstorsjo/msvc-wine#28]
Thanks for this, very cool!

Do you know of any way to get the kernel-mode headers as well? There should be a `km` directory, alongside `um` and `shared`, containing `ntifs.h` and the like (i.e. what's in /usr/include/ddk for mingw). I had a brief look in Microsoft's package listing but couldn't see anything obvious.

**Comment by maharmstone** [comment]
Thanks @Biswa96, that was helpful. The files are in `Installers/Windows Driver Kit Headers and Libs-x86_en-us.msi` and `Installers/Windows Driver Kit ARM Headers and Libs-x86_en-us.msi` of the ISO.

**Comment by maharmstone** [comment]
Thanks Martin and @ravenexp for this - I'll give it a go. It should make my workflow a lot simpler.

**Comment by ravenexp** [comment]
> Thanks Martin and @ravenexp for this - I'll give it a go. It should make my workflow a lot simpler.

The main remaining blocking issue for me is that I can not sign the drivers I build on Linux. Both `inf2cat.exe` and `signtool.exe` do not work in WINE yet.

There are OSS alternatives such as https://github.com/LINBIT/generate-cat-file and https://github.com/mtrojnar/osslsigncode, but I still haven't got around to try them. If you have any success with these tools, then we could maybe add links to them to the README.

**Comment by maharmstone** [comment]
> The main remaining blocking issue for me is that I can not sign the drivers I build on Linux. Both `inf2cat.exe` and `signtool.exe` do not work in WINE yet.
> 
> There are OSS alternatives such as https://github.com/LINBIT/generate-cat-file and https://github.com/mtrojnar/osslsigncode, but I still haven't got around to try them. If you have any success with these tools, then we could maybe add links to them to the README.

Yes, this was something that was always problematic for me in the past. I could never get osslsigncode to work. I'd not heard of generate-cat-file, but it looks like it only does SHA1 hashes, and IIRC some versions of Windows require SHA256.

**Comment by maharmstone** [comment]
I couldn't find any free way to make cat files, so ended up making my own clone of Microsoft's makecat: https://github.com/maharmstone/nyan.

**Comment by ravenexp** [comment]
> I couldn't find any free way to make cat files, so ended up making my own clone of Microsoft's makecat: https://github.com/maharmstone/nyan.

Wow, this is great news! I was thinking of trying to hack `osslsigncode` to make it output `.cat` files, since it already knows how to calculate Authenticode PE hashes. Unfortunately, I don't have any free time for this atm...

BTW, the current version of `osslsigncode` can sign `.cat` files out of the box. Does this work for you when used together with `nyan`? I'm only really interested in test signing with self-signed certificates. I'll try to test it myself as soon as I can, but it won't happen until next week or even next month.

**Comment by maharmstone** [comment]
>BTW, the current version of osslsigncode can sign .cat files out of the box. Does this work for you when used together with nyan?

Yes. I've got a CI job on my private Gitea server that produces signed files that can be installed on a clean Windows installation. You might want to crib from https://github.com/maharmstone/btrfs/blob/master/.github/workflows/build.yml, it was a bit tricky to get right.

**Comment by ravenexp** [comment]
> You might want to crib from https://github.com/maharmstone/btrfs/blob/master/.github/workflows/build.yml, it was a bit tricky to get right.

Thanks for the tip! I'll give it a try ASAP.
