### ISSUE TITLE
Most scripts included hardcodely point to /opt/msvc2017 yet provided script installs at /opt/msvc

### ISSUE THREAD

**Issue by samzanemesis** [mstorsjo/msvc-wine#3]
The file https://github.com/mstorsjo/msvc-wine/blob/master/wrappers/msvcenv.sh and `Dockerfile.hello` for example points often to `/opt/msvc2017/` as the root path of the installation yet the script installs everything at `/opt/msvc/`

**Comment by mstorsjo** [comment]
Thanks for reporting - apparently I overlooked this when updating the path in 2eecc569a73cc748342f568e30fbcf7733432970.

The path in msvcenv.sh doesn't matter though; install.sh overwrites it when it actually is installed (but it obviously still should be kept consistent), but the one in Dockerfile.hello indeed is fatal.
