### ISSUE TITLE
wine64 is needed instead of wine for x64 toolchain on Ubuntu 20.04

### ISSUE THREAD

**Issue by dmikushin** [mstorsjo/msvc-wine#30]
Hi @mstorsjo ,

On Ubuntu 20.04 wine is no longer able to execute 64-bit Windows apps. In order to get it to work, I needed to call wine64 instead of wine explicitly. The change to the script could be like this:

```
Small fix to the Martin's original scripts: wine64 should be used for x64.
RUN sed -i "s/wine /win64 /" /opt/msvc/bin/x64/wine-msvc.sh
```

Thanks！you are so great。(c)

**Comment by johnsonjh** [comment]
Looks like this is fixed and can be closed.
