### ISSUE TITLE
No instructions on how to use with CMake, or any other build system for that matter.

### ISSUE THREAD

**Issue by HFDan** [mstorsjo/msvc-wine#31]
It would be nice for there to be available insttuctions on how to use with CMake. Currently, there are none, and compiling using the bash wrappers as compilers in cmake with CMAKE_C_COMPILER_WORKS=1 and CMAKE_CXX_COMPILER_WORKS=1 seems to either be **very** slow, or just plain hangs.

A toolchain file would be much appreciated.

**Comment by mstorsjo** [comment]
See https://github.com/mstorsjo/msvc-wine/commit/cmake for an example on how to use it with cmake, including building patched cmake/ninja.

It's not exactly great front-and-center documentation, but it also kinda doesn't work perfectly with cmake/ninja out of the box, without a couple tweaks. In #29 there's ongoing discussion about a change that could reduce the amount of changes needed to cmake/ninja though.

**Comment by HFDan** [comment]
> See https://github.com/mstorsjo/msvc-wine/commit/cmake for an example on how to use it with cmake, including building patched cmake/ninja.
> 
> It's not exactly great front-and-center documentation, but it also kinda doesn't work perfectly with cmake/ninja out of the box, without a couple tweaks. In #29 there's ongoing discussion about a change that could reduce the amount of changes needed to cmake/ninja though.

I actually am using this **outside** of a container. MSVC is installed in /opt/msvc.

**Comment by mstorsjo** [comment]
Containers or not doesn't matter, but that Dockerfile gives pointers to my patches for cmake and ninja, commands for how to build exactly those patched versions, and shows examples how to invoke cmake to build things with it. It doesn't need a toolchain file - it's enough to invoke it with e.g. `CC=cl CXX=cl cmake -G Ninja [...]`. But for now, it probably works best if you use the patched cmake and ninja versions that I reference.

**Comment by HFDan** [comment]
I made CMake toolachain files for this: https://gist.github.com/HFDan/618bad4c01cacf7198b68162ac07750c

How to use:
1. `wineserver -p`
2. `wine wineboot`
3. `cmake <Your arguments> -DCMAKE_TOOLCHAIN_FILE=<Absolute Toolchain File Path> -G Ninja`
4. `cd <Build Dir>`
5. `ninja`

If the build seems to hang, or take too long:
1. Send interrupt with `Ctrl+C`
2. Delete the build folder
3. Regenerate cache
4. Build again

When you are done with msvc, remember to run `wineserver -k`

Just make sure to use Ninja and build in Release mode. Debug does not seem to work atm.
