### ISSUE TITLE
The CMake fork's msvc branch is based on cmake 3.16, which is now ~2 years old

### ISSUE THREAD

**Issue by Username404-59** [mstorsjo/msvc-wine#36]
Could you please update it to CMake 3.22 by rebasing it onto cmake's release branch?

**Comment by mstorsjo** [comment]
I rebased that cmake branch now, see the update in 9ebc76c16e5849438ddb6566042af87dcff0ca1e here (pointing at 844ccd2280d11ada286d0e2547c0fa5ff22bd4db in https://gitlab.kitware.com/mstorsjo/cmake.git).

**Comment by Username404-59** [comment]
Thanks you!
