### ISSUE TITLE
LLVM DIA SDK

### ISSUE THREAD

**Issue by yuanfang-chen** [mstorsjo/msvc-wine#38]
LLVM DIA SDK support seems to need the ATL package ("Microsoft.VisualStudio.Component.VC.ATL"). Add it to the default package since DIA SDK is included already?

https://github.com/llvm/llvm-project/blob/7ee1c162cc53d37f717f9a138276ad64fa6863bc/llvm/include/llvm/DebugInfo/PDB/DIA/DIASupport.h#L25

**Comment by mstorsjo** [comment]
Thanks, you're right that I hadn't really tried out the DIA SDK support here.

I pushed an experimental branch here, at https://github.com/mstorsjo/msvc-wine/commit/atl, which installs this package too. I think this seems to work for building LLVM with DIA SDK enabled.

I guess if we do this, we should also add this package consistently to the versioned install targets, if installing with e.g. `--msvc-16.3` - what do you think?

**Comment by yuanfang-chen** [comment]
> Thanks, you're right that I hadn't really tried out the DIA SDK support here.
> 
> I pushed an experimental branch here, at [atl](https://github.com/mstorsjo/msvc-wine/commit/atl), which installs this package too. I think this seems to work for building LLVM with DIA SDK enabled.
> 
> I guess if we do this, we should also add this package consistently to the versioned install targets, if installing with e.g. `--msvc-16.3` - what do you think?

Thanks a lot for the quick response. Yeah, I think it makes sense to add ATL to the versioned install targets.

**Comment by mstorsjo** [comment]
I merged #143 now, so this should be fixed now.
