### ISSUE TITLE
Sed: unterminated `s' command

### ISSUE THREAD

**Issue by rom4s** [mstorsjo/msvc-wine#4]
If the folder name begins, for example, with "t", then after replacing forward slashes with backslashes, the next sed call causes an error. Apparently \t converts to TAB?

For example: **/home/a/tools/msvc**
Renaming the folder from **tools** to **dtools** solves the problem.

> sed: -e expression #1, char 37: unterminated `s' command

**Comment by rom4s** [comment]
and..
![image](https://user-images.githubusercontent.com/12962908/73485175-71caf980-43c4-11ea-9244-64c128ebb6d3.png)

**Comment by mstorsjo** [comment]
I believe this is fixed in 2dc5e29e5aafed7f04bd89d6b21a675c8b6cb338.
