### ISSUE TITLE
Add LICENSE for entire repo

### ISSUE THREAD

**Issue by real-or-random** [mstorsjo/msvc-wine#42]
I see that vsdownload.py has a license inline (ISC?) but the other code has not. Are you willing and would you mind adding a `LICENSE` or `LICENSE.txt`?

And thanks, this project is very useful. I use it to test code on MSVC without having to resort to a Windows machine.

**Comment by mstorsjo** [comment]
Sure, I could add such a file. It needs to make clear that it only covers these scripts, not the stuff that it downloads and installs though...

**Comment by real-or-random** [comment]
Ok yes, I think this is implied, but it can't hurt to say it explicitly.

**Comment by mstorsjo** [comment]
Done in 2f011e286acbc0725b33fe551f9b212167f415c8.

**Comment by real-or-random** [comment]
Thanks!
