### ISSUE TITLE
Some files are not lowercased?

### ISSUE THREAD

**Issue by somebody1234** [mstorsjo/msvc-wine#48]
I'm probably doing something *very* wrong, but `concrt` seems to be missed by `lowercase`? (`vc/tools/msvc/14.32.31326/crt/src/concrt/`)

(specofically, `Platform.h`)

**Comment by mstorsjo** [comment]
The install script only lowercases the directories that are expected to be needed in lowercase form, i.e. the include and lib directories. AFAIK nothing uses things from that directory automatically? Feel free to lowercase the directory manually if you have a need for it though.

**Comment by somebody1234** [comment]
okay, fair enough
