### ISSUE TITLE
Incorrect path for x86,arm,arm64

### ISSUE THREAD

**Issue by rom4s** [mstorsjo/msvc-wine#5]
![image](https://user-images.githubusercontent.com/12962908/73485375-ce2e1900-43c4-11ea-97ab-31c834ee6421.png)

**Comment by mstorsjo** [comment]
No, this is correct and as intended.

The executables e.g. `msvc/bin/arm64` are for compiling code that will run on arm64. In this case, BINDIR is set to something like `$MSVCVER/bin/Hostx64/arm64` - this is the directory that contains compiler binaries that _run on_ x64, but produces code for arm64. There's no `Hostarm64` directory, as the compiler isn't available for running on arm64, on for compiling on x86.

For SDKBINDIR, all the binaries there work for any target architecture.

And WINEPATH is only used for picking up some extra dependency DLLs that aren't available in all of the HostXXX/YYY directories.
