### ISSUE TITLE
output of `/showIncludes /scanDependencies` not translated

### ISSUE THREAD

**Issue by huangqinjin** [mstorsjo/msvc-wine#57]
#### `main.cpp`
```cxx
#include <stdio.h>
```

#### without `/scanDependencies`
```shell
$ /opt/msvc/bin/x64/cl.exe /c main.cpp /showIncludes
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32502 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
Note: including file: /opt/msvc/kits/10/include/10.0.22621.0/ucrt/stdio.h
Note: including file:  /opt/msvc/kits/10/include/10.0.22621.0/ucrt/corecrt.h
Note: including file:   /opt/msvc/vc/tools/msvc/14.36.32502/include/vcruntime.h
Note: including file:    /opt/msvc/vc/tools/msvc/14.36.32502/include/sal.h
Note: including file:     /opt/msvc/vc/tools/msvc/14.36.32502/include/concurrencysal.h
Note: including file:    /opt/msvc/vc/tools/msvc/14.36.32502/include/vadefs.h
Note: including file:  /opt/msvc/kits/10/include/10.0.22621.0/ucrt/corecrt_wstdio.h
Note: including file:   /opt/msvc/kits/10/include/10.0.22621.0/ucrt/corecrt_stdio_config.h
```

#### with `/scanDependencies`
```shell
$ /opt/msvc/bin/x64/cl.exe /c main.cpp /showIncludes /scanDependencies main.cpp.obj.ddi
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32502 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
Note: including file: z:\opt\msvc\kits\10\include\10.0.22621.0\ucrt\stdio.h
Note: including file:  z:\opt\msvc\kits\10\include\10.0.22621.0\ucrt\corecrt.h
Note: including file:   z:\opt\msvc\vc\tools\msvc\14.36.32502\include\vcruntime.h
Note: including file:    z:\opt\msvc\vc\tools\msvc\14.36.32502\include\sal.h
Note: including file:     z:\opt\msvc\vc\tools\msvc\14.36.32502\include\concurrencysal.h
Note: including file:    z:\opt\msvc\vc\tools\msvc\14.36.32502\include\vadefs.h
Note: including file:  z:\opt\msvc\kits\10\include\10.0.22621.0\ucrt\corecrt_wstdio.h
Note: including file:   z:\opt\msvc\kits\10\include\10.0.22621.0\ucrt\corecrt_stdio_config.h
```

### Additional Information
Seems if `/scanDependencies` is not specified, `/showIncludes` output to `stdout`, otherwise `/showIncludes` output to `stderr`.

**Comment by mstorsjo** [comment]
Thanks for the report, this should be fixed by https://github.com/mstorsjo/msvc-wine/commit/635a3aa148a42f701b3e46dd13791a01a3cf87f6.

**Comment by huangqinjin** [comment]
Including `iostream` for test, I found `stderr` of `wine` and `cl`  interleave.

```
...
Note: including file:         /opt/msvc/kits/10/include/10.0.22621.0/ucrt/wchar.h
Note: including file:          /opt/msvc/kits/10/include/10.0.22621.0/ucrt0024:fixme:file:server_get_file_info Unsupported info class 33
\corecrt_wconio.h
Note: including file:          /opt/msvc/kits/10/include/10.0.22621.0/ucrt/corecrt_wctype.h
...
```

I think we should suppress all outputs of `wine` by [WINEDEBUG=-all](https://wiki.winehq.org/Debug_Channels).

**Comment by mstorsjo** [comment]
> Including `iostream` for test, I found `stderr` of `wine` and `cl` interleave.
> 
> ```
> ...
> Note: including file:         /opt/msvc/kits/10/include/10.0.22621.0/ucrt/wchar.h
> Note: including file:          /opt/msvc/kits/10/include/10.0.22621.0/ucrt0024:fixme:file:server_get_file_info Unsupported info class 33
> \corecrt_wconio.h
> Note: including file:          /opt/msvc/kits/10/include/10.0.22621.0/ucrt/corecrt_wctype.h
> ...
> ```
> 
> I think we should suppress all outputs of `wine` by [WINEDEBUG=-all](https://wiki.winehq.org/Debug_Channels).

Right, if something is parsing the output from stderr, then we probably must do that.

I'm not familiar with the use case of `/scanDependencies`, can you explain where/how it's used. Do cmake set that up, and does it make ninja parse the output of stderr instead of stdout?
