### ISSUE TITLE
Installation failed on macOS: Too many levels of symbolic links

### ISSUE THREAD

**Issue by huangqinjin** [mstorsjo/msvc-wine#66]
macOS uses a case-insensitive filesystem.

**Comment by mstorsjo** [comment]
This issue should be fixed by the commits in https://github.com/mstorsjo/msvc-wine/commits/macos (which also adds a CI setup for this case). If you think those commits look fine, I could push them to the master branch.

**Comment by huangqinjin** [comment]
As I stated in https://github.com/mstorsjo/msvc-wine/pull/65#issuecomment-1531747302 , using fifo works on macOS. So kindly push the CI changes, than I will rebase on top of it.

**Comment by mstorsjo** [comment]
> As I stated in [#65 (comment)](https://github.com/mstorsjo/msvc-wine/pull/65#issuecomment-1531747302) , using fifo works on macOS. So kindly push the CI changes, than I will rebase on top of it.

Ok, that's done in c64b8f94ce9a6a2be5f5cdc4ae1e0d6f6503b028 now.

**Comment by huangqinjin** [comment]
Thanks for the fix!
