### ISSUE TITLE
LIB environmental variable needs : and not ;

### ISSUE THREAD

**Issue by coderforlife** [mstorsjo/msvc-wine#90]
I noticed issues when trying to include libraries that are on the `$LIB` path. A simple example is as follows using the docker image provided (and some additional parts from Dockerfile.clang to have hello.c and clang installed [although I am using `clang-cl-10` and not 14 like in that image]):

```sh
export BIN=/opt/msvc/bin/x64
export PATH="$BIN:$PATH"

/opt/msvc/msvcenv-native.sh
echo $LIB  # /opt/msvc/vc/tools/msvc/14.37.32822/lib/x64;/opt/msvc/kits/10/lib/10.0.22621.0/ucrt/x64;/opt/msvc/kits/10/lib/10.0.22621.0/um/x64

clang-cl hello.c -o test.exe kernel32.lib  # clang: error: no such file or directory: 'kernel32.lib'

export LIB="$(echo "$LIB" | sed 's/;/:/g')"
echo "$LIB"  # /opt/msvc/vc/tools/msvc/14.37.32822/lib/x64:/opt/msvc/kits/10/lib/10.0.22621.0/ucrt/x64:/opt/msvc/kits/10/lib/10.0.22621.0/um/x64

clang-cl hello.c -o test.exe kernel32.lib  # compiles just fine
```

I know that in this case, kernel32.lib isn't actually needed, but it is just to show that the lib cannot be found unless `:` is used in `$LIB`.

I do not know if this is version-specific, e.g. maybe this happens with `clang-cl-10` but not `clang-cl-14` or maybe only with certain versions of the MSVC library. If all versions require `:` then it is an easy fix (just add `| sed 's/;/:/g'` into `msvcenv-native.sh` where you are already processing the environmental variables). If not, it will require being much more clever...

**Comment by mstorsjo** [comment]
This is indeed a change since Clang 12 - see https://github.com/llvm/llvm-project/commit/3fec6ddc276a595e4409f04dabdd50c84f5f2a2d. Before this, Clang already split `$INCLUDE` around semicolons, and lld split `$LIB` around semicolons, so this change made Clang's use of `$LIB` consistent with those.

**Comment by coderforlife** [comment]
Gotcha. I have actually now run into other problems with Clang 10 (although this time need clang 16 to work... some part of the standard library headers have an error "Unexpected compiler version, expected Clang 16.0.0 or newer."). I was only using 10 since it came with the Ubuntu of your image.
