### ISSUE TITLE
 vsdownload.py: option to download compiler

### ISSUE THREAD

**Issue by 3052** [mstorsjo/msvc-wine#94]
I think the current script only download libraries and/or headers, it would be nice if an option was available to also download the Microsoft compiler. this would obviate the need for users to have to also install the Clang compiler or similar

**Comment by mstorsjo** [comment]
No. The scripts download both the libraries and headers, and the Microsoft compiler, so you don’t need clang. You can, optionally, use them with clang too.

**Comment by 3052** [comment]
thanks. just to be clear, you are saying "no, I wont add the option, because the script already downloads the compiler as well"?

**Comment by mstorsjo** [comment]
The script already downloads the compiler.
