### ISSUE TITLE
there seems to be no wine64 in ubuntu23.10

### ISSUE THREAD

**Issue by ririyeye** [mstorsjo/msvc-wine#99]
only `wine` not `wine64` in new version ubuntu 23.10
i add a symbol link wine64 -> wine in system

**Comment by johnsonjh** [comment]
@ririyeye @mstorsjo 

Instead of using ...
```sh
wine64
```
... the shell scripts could be changed to use
```sh
$(command -v wine64 || command -v wine || false)
```

**Comment by johnsonjh** [comment]
Opened https://github.com/mstorsjo/msvc-wine/pull/107 to test.
